name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@master
        with:
          node-version: 20
      
      - name: Install Node tools
        run: npm install

      - name: Setting Github Token
        run: export GH_TOKEN="${{ secrets.github_token }}"
        
      - name: Build electron app
        run: npm run build

      - name: Packaging electron app
        run: npm run package
        
